# Generated by Django 6.0.1 on 2026-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('S-F', 'Science-Fiction'), ('ROM', 'Roman'), ('FAN', 'Fantasy')], max_length=3)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
